[package]
name = "cli_project"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
serde = { version = "1.0.223", features=["derive"]}
serde_json = "1.0.145"
ellipse = "0.2.0"
itertools = "0.14.0"

[dev-dependencies]
tempfile= "3.22.0"